// Word counts calculated with https://pengowray.github.io/word-count-epub/
// (with include non-toc items on)

const shelves = {
  Current: [
    {
      series: 'Twig',
      entry: 'Arc 17',
      title: 'Gut Feeling',
      author: 'Wildbow',
      words: 87287,
      size: 'large',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 1',
      title: '1805',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 47964,
      size: 'tiny',
    },
    {
      series: 'Tanakh',
      title: 'Torah',
      author: 'RJPS',
      words: 150152,
      size: 'large',
    },
  ],
  'Jul 2026': [
    {
      title: 'Thirteen Storeys',
      author: 'Jonathan Sims',
      words: 110783,
      size: 'medium',
    },
  ],
  'Jun 2026': [
    {
      title: 'Valuable Humans in Transit and Other Stories',
      author: 'qntm',
      words: 22156,
      size: 'tiny',
    },
    {
      series: 'Twig',
      entry: 'Arc 16',
      title: 'Head over Heels',
      author: 'Wildbow',
      words: 73805,
      size: 'large',
    },
    {
      title: 'Infect Your Friends and Loved Ones',
      author: 'Torrey Peters',
      words: 12801,
      size: 'tiny',
    },
    {
      series: 'Arc of a Scythe',
      entry: '#3',
      title: 'The Toll',
      author: 'Neal Shusterman',
      words: 146547,
      size: 'medium',
    },
    {
      series: 'Twig',
      entry: 'Arc 15',
      title: 'Bitter Pill',
      author: 'Wildbow',
      words: 85925,
      size: 'large',
    },
  ],
  'May 2026': [
    {
      series: 'Arc of a Scythe',
      entry: '#2',
      title: 'Thunderhead',
      author: 'Neal Shusterman',
      words: 121691,
      size: 'medium',
    },
    {
      series: 'Twig',
      entry: 'Arc 14',
      title: 'Thicker than Water',
      author: 'Wildbow',
      words: 99454,
      size: 'large',
    },
    {
      series: 'Arc of a Scythe',
      entry: '#1',
      title: 'Scythe',
      author: 'Neal Shusterman',
      words: 103307,
      size: 'medium',
    },
    {
      title: 'The Disaster Artist',
      author: 'Greg Sestero<br>Tom Bissell',
      words: 99922,
      size: 'medium',
    },
    {
      series: 'This Used to be <br> About Dungeons',
      entry: 'Volume 1',
      author: 'Alexander Wales',
      words: 205235,
      size: 'large',
    },
  ],
  // Books I have on my kindle, so it's easier to add them to this page
  /*
  Kindle: [
    {
      series: 'Twig',
      entry: 'Arc 17',
      title: 'Gut Feeling',
      author: 'Wildbow',
      words: 87287,
      size: 'large',
    },
    {
      series: 'Twig',
      entry: 'Arc 18',
      title: 'Dog Eat Dog',
      author: 'Wildbow',
      words: 98018,
      size: 'large',
    },
    {
      series: 'Twig',
      entry: 'Arc 19',
      title: 'Root and Branch',
      author: 'Wildbow',
      words: 86578,
      size: 'large',
    },
    {
      series: 'Twig',
      entry: 'Arc 20',
      title: 'Crown of Thorns',
      author: 'Wildbow',
      words: 102321,
      size: 'large',
    },
    {
      series: 'Twig',
      entry: 'Arc e',
      title: 'Forest for the Trees',
      author: 'Wildbow',
      words: 22512,
      size: 'small',
    },
    {
      series: 'This Used to be <br> About Dungeons',
      entry: 'Volume 2',
      author: 'Alexander Wales',
      words: 181201,
      size: 'large',
    },
    {
      series: 'This Used to be <br> About Dungeons',
      entry: 'Volume 3',
      author: 'Alexander Wales',
      words: 206847,
      size: 'large',
    },
    {
      series: 'Farseer Trilogy',
      entry: '#1',
      title: "Assassin's Apprentice",
      author: 'Robin Hobb',
      words: 157249,
      size: 'large',
    },
    {
      series: 'Farseer Trilogy',
      entry: '#2',
      title: 'Royal Assassin',
      author: 'Robin Hobb',
      words: 260474,
      size: 'large',
    },
    {
      series: 'Farseer Trilogy',
      entry: '#3',
      title: "Assassin's Quest",
      author: 'Robin Hobb',
      words: 332974,
      size: 'large',
    },
    {
      title: "Howl's Moving Castle",
      author: 'Diana Wynne Jones',
      words: 74394,
      size: 'medium',
    },
    {
      title: 'To Sleep in a Sea of Stars',
      author: 'Christopher Paolini',
      words: 309103,
      size: 'large',
    },
    {
      title: 'The Metropolitan Man',
      author: 'Alexander Wales',
      words: 76905,
      size: 'medium',
    },
    {
      title:
        'Meanwhile, Elsewhere:<br>Science Fiction and Fantasy<br>from Transgender Writers',
      author: 'Cat Fitzpatrick<br>Casey Plett',
      words: 174684,
      size: 'medium',
    },
    {
      title: 'Ra',
      author: 'qntm',
      words: 141955,
      size: 'medium',
    },
    {
      title: 'Fine Structure',
      author: 'qntm',
      words: 100612,
      size: 'medium',
    },
    {
      title: 'jan Osawi pi ma Osawi',
      author: 'eng: L. Frank Baum<br>tok: jan Ke Tami',
      words: 49357,
      size: 'small',
    },
    {
      title: 'Autobiography of an Androgyne',
      author: 'Jennie June',
      words: 80789,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '#1',
      title: 'Dune',
      author: 'Frank Herbert',
      words: 206772,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '#2',
      title: 'Dune: Messiah',
      author: 'Frank Herbert',
      words: 75200,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '#3',
      title: 'Children of Dune',
      author: 'Frank Herbert',
      words: 149047,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '#4',
      title: 'God Emperor of Dune',
      author: 'Frank Herbert',
      words: 138954,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '#5',
      title: 'Heretics of Dune',
      author: 'Frank Herbert',
      words: 168801,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '#6',
      title: 'Chapterhouse: Dune',
      author: 'Frank Herbert',
      words: 143579,
      size: 'medium',
    },
    {
      title: 'Little Blue Encyclopedia',
      author: 'Hazel Jane Plante',
      words: 43853,
      size: 'medium',
    },
    {
      series: 'Alex Stern',
      entry: '#1',
      title: 'Ninth House',
      author: 'Leigh Bardugo',
      words: 141294,
      size: 'medium',
    },
    {
      title: 'Family Business',
      author: 'Jonathan Sims',
      words: 95600,
      size: 'medium',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 2',
      title: '1805',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 40532,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 3',
      title: '1805',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 44118,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 4',
      title: '1806',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 23496,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 5',
      title: '1806 - 07',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 33642,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 6',
      title: '1808 - 10',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 33352,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 7',
      title: '1810 - 11',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 22839,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 8',
      title: '1811 - 12',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 30950,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 9',
      title: '1812',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 37871,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 10',
      title: '1812',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 64773,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 11',
      title: '1812',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 51933,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 12',
      title: '1812',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 24329,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 13',
      title: '1812',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 20178,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 14',
      title: '1812',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 20576,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Book 15',
      title: '1812 - 13',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 24249,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'First Epilogue',
      title: '1813 - 20',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 24145,
      size: 'tiny',
    },
    {
      series: 'War and Peace<br>',
      entry: 'Second Epilogue',
      title: '',
      author: 'rus: Leo Tolstoy<br>eng: A. + L. Maude',
      words: 17560,
      size: 'tiny',
    },
    {
      title: 'Girlfriends',
      author: 'Emily Zhou',
      words: 50540,
      size: 'medium',
    },
  ],
  */
};
