// Word counts calculated with https://pengowray.github.io/word-count-epub/
// (with include non-toc items on)

const shelves = {
  Current: [
    {
      series: 'Twig',
      entry: '16',
      title: 'Head over Heels',
      author: 'Wildbow',
      words: 73805,
      size: 'large',
    },
    {
      title: 'Valuable Humans in Transit and Other Stories',
      author: 'qntm',
      words: 22156,
      size: 'small',
    },
    {
      series: 'Tanakh',
      title: 'Torah',
      author: 'RJPS',
      words: 150152,
      size: 'large',
    },
  ],
  'Jun 2026': [
    {
      series: 'Arc of a Scythe',
      entry: '3',
      title: 'The Toll',
      author: 'Neal Shusterman',
      words: 146547,
      size: 'medium',
    },
    {
      series: 'Twig',
      entry: '15',
      title: 'Bitter Pill',
      author: 'Wildbow',
      words: 85925,
      size: 'large',
    },
  ],
  'May 2026': [
    {
      series: 'Arc of a Scythe',
      entry: '2',
      title: 'Thunderhead',
      author: 'Neal Shusterman',
      words: 121691,
      size: 'medium',
    },
    {
      series: 'Twig',
      entry: '14',
      title: 'Thicker than Water',
      author: 'Wildbow',
      words: 99454,
      size: 'large',
    },
    {
      series: 'Arc of a Scythe',
      entry: '1',
      title: 'Scythe',
      author: 'Neal Shusterman',
      words: 103307,
      size: 'medium',
    },
    {
      title: 'The Disaster Artist',
      author: 'Greg Sestero & Tom Bissell',
      words: 99922,
      size: 'medium',
    },
    {
      series: 'This Used to be <br> About Dungeons',
      entry: '1',
      author: 'Alexander Wales',
      words: 205235,
      size: 'large',
    },
  ],
  // Books I have on my kindle, so it's easier to add them to this page
  /*
  Kindle: [
    {
      series: 'Twig',
      entry: '17',
      title: 'Gut Feeling',
      author: 'Wildbow',
      words: 87287,
      size: 'large',
    },
    {
      series: 'Twig',
      entry: '18',
      title: 'Dog Eat Dog',
      author: 'Wildbow',
      words: 98018,
      size: 'large',
    },
    {
      series: 'Twig',
      entry: '19',
      title: 'Root and Branch',
      author: 'Wildbow',
      words: 86578,
      size: 'large',
    },
    {
      series: 'Twig',
      entry: '20',
      title: 'Crown of Thorns',
      author: 'Wildbow',
      words: 102321,
      size: 'large',
    },
    {
      series: 'Twig',
      entry: 'e',
      title: 'Forest for the Trees',
      author: 'Wildbow',
      words: 22512,
      size: 'small',
    },
    {
      series: 'This Used to be <br> About Dungeons',
      entry: '2',
      author: 'Alexander Wales',
      words: 181201,
      size: 'large',
    },
    {
      series: 'This Used to be <br> About Dungeons',
      entry: '3',
      author: 'Alexander Wales',
      words: 206847,
      size: 'large',
    },
    {
      series: 'Farseer Trilogy',
      entry: '1',
      title: "Assassin's Apprentice",
      author: 'Robin Hobb',
      words: 157249,
      size: 'large',
    },
    {
      series: 'Farseer Trilogy',
      entry: '2',
      title: 'Royal Assassin',
      author: 'Robin Hobb',
      words: 260474,
      size: 'large',
    },
    {
      series: 'Farseer Trilogy',
      entry: '3',
      title: "Assassin's Quest",
      author: 'Robin Hobb',
      words: 332974,
      size: 'large',
    },
    {
      title: "Howl's Moving Castle",
      author: 'Diana Wynne Jones',
      words: 74394,
      size: 'medium',
    },
    {
      title: 'To Sleep in a Sea of Stars',
      author: 'Christopher Paolini',
      words: 309103,
      size: 'large',
    },
    {
      title: 'The Metropolitan Man',
      author: 'Alexander Wales',
      words: 76905,
      size: 'medium',
    },
    {
      title:
        'Meanwhile, Elsewhere:<br>Science Fiction and Fantasy<br>from Transgender Writers',
      author: 'Fitzpatrick & Plett',
      words: 174684,
      size: 'medium',
    },
    {
      title: 'Ra',
      author: 'qntm',
      words: 141955,
      size: 'medium',
    },
    {
      title: 'Fine Structure',
      author: 'qntm',
      words: 100612,
      size: 'medium',
    },
    {
      title: 'jan Osawi pi ma Osawi',
      author: 'L. Frank Baum<br>trans. jan Ke Tami',
      words: 49357,
      size: 'small',
    },
    {
      title: 'Autobiography of an Androgyne',
      author: 'Jennie June',
      words: 80789,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '1',
      title: 'Dune',
      author: 'Frank Herbert',
      words: 206772,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '2',
      title: 'Dune: Messiah',
      author: 'Frank Herbert',
      words: 75200,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '3',
      title: 'Children of Dune',
      author: 'Frank Herbert',
      words: 149047,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '4',
      title: 'God Emperor of Dune',
      author: 'Frank Herbert',
      words: 138954,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '5',
      title: 'Heretics of Dune',
      author: 'Frank Herbert',
      words: 168801,
      size: 'medium',
    },
    {
      series: 'Dune',
      entry: '6',
      title: 'Chapterhouse: Dune',
      author: 'Frank Herbert',
      words: 143579,
      size: 'medium',
    },
    {
      title: 'War and Peace',
      author: 'Leo Tolstoy<br>trans. Aylmer & Louise Maude',
      words: 566355,
      size: 'large',
    },
    {
      title: 'Little Blue Encyclopedia',
      author: 'Hazel Jane Plante',
      words: 43853,
      size: 'medium',
    },
    {
      series: 'Alex Stern',
      entry: '1',
      title: 'Ninth House',
      author: 'Leigh Bardugo',
      words: 141294,
      size: 'medium',
    },
    {
      title: 'Thirteen Storeys',
      author: 'Jonathan Sims',
      words: 110783,
      size: 'medium',
    },
    {
      title: 'Family Business',
      author: 'Jonathan Sims',
      words: 95600,
      size: 'medium',
    },
    {
      // Todo: when i read this one add a tiny font and a tiny book class
      title: 'Infect Your Friends and Loved Ones',
      author: 'Torrey Peters',
      words: 12801,
      size: 'small',
    },
  ],
  */
};
