let quotes = [
  'You have the power to heal your life, and you need to know that.',
  "They don't know that we know they know we know.",
  "Don't it make you sad to know that life is more than who you are?",
  "Leave something for someone but don't leave someone for something.",
  'The people with ideas have no power and the people with power have no ideas.',
  'You must take life the way it comes at you and make the best of it.',
  "If you don't know what you want, how are you going to know when you get it?",
  'If you have to ask, you will never know. If you know, you need only ask.',
  'Your memory is the glue that binds your life together.',
  "I'm sure there are things you know that you don't even know you know.",
  "You can't use the fire exit because you're not made of fire.",
  'The person that has the most to do with what happens to you is you!',
  'There are darknesses in life and there are lights, and you are one of the lights, the light of all lights.',
  'Sometimes the world as you know it just decides to become something else.',
  'If you only do what you can do, you will never be more than who you are now.',
  'If I have to hear one more time that you did this for the family...',
  'And in the end, the love you take is equal to the love you make.',
  "I've always loved you, and when you love someone, you love the whole person, just as he or she is, and not as you would like them to be.",
  'Memory is a way of holding onto the things you love, the things you are, the things you never want to lose.',
  'You should never, never doubt something that no one is sure of.',
  'Make sure you marry someone who laughs at the same things you do.',
  'If you think that you are going to love something, give it a try.',
  "I have waited lifetimes to find you. Now that you're here I can remind you of the things you've been dreaming, times two.",
  'Are you trying to impress me? What would impress me more is if you never did that again.',
  "Yeah it's you, you're the one that makes me feel right. I've been in love with her for ages and I can't seem to get it right. I fell in love with her in stages my whole life.",
  'Believe in one thing too much and you have no room for new ideas.',
  "Cleaning your house while kids are around is like shoveling the walk while it's still snowing.",
  'The day the power of love overrules the love of power, the world will know peace.',
  'I am the wisest man alive, for I know one thing, and that is that I know nothing.',
  "You can't convince me what I want and what I need are separate things.",
  "It's easy not to abuse your power when you don't actually have any power.",
  "I often think that men don't understand what is noble and what is ignorant, though they always talk about it.",
  "Now is the time for resting. Some things are ill to hear when the world's in shadow.",
  'Courage is resistance to fear, mastery of fear - not absence of fear.',
  "There's no reason a fake can't do what the real thing would. And it's possible for a fake to be more real than the real thing.",
  'It matters not how a man dies, but how he lives. The act of dying is not of importance, it lasts so short a time.',
  "There is something about yourself that you don't know.",
  'I am he as you are he as you are me and we are all together.',
  'Anything is edible if you deep fry it long enough.',
  'There will come a time when all of us are dead.',
  'We know little of who we were, only something of who we are, and nothing of who we may be.',
  "You know when I was a kid I always wanted to be a cowboy, and now knowing I'm going to spend my future in the past sounds like a wonderful way to spend my retirement years.",
  'When we remember, we only get a version of the last time we remember it.',
  'When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.',
  "Where do you think you're going? Because I don't think you're going where you think you're going.",
  "When everyone else was thinking it was time for bed, his mind was telling him it's time to get ahead of the competition.",
  "You must learn from the mistakes of others because you can't possibly live long enough to make them all yourself.",
  'I would rather spend one lifetime with you, than face all the ages of this world alone.',
  'You can get more of what you want with a kind word and a gun than you can with just a kind word.',
  'Thinking you know everything there is to know about something will only hold you back, because it prevents you from learning anything new.',
  "Sometimes it takes heart to write about a thing, doesn't it? To let that thing out of the room way in the back of your mind and put it up there on the screen.",
  "I'm going to take my time. I have all the time in the world.",
  'You are what you are and you are where you are because of what has gone into your mind. You change what you are and you change where you are by changing what goes into your mind.',
  "There are many things that I would like to say to you but I don't know how.",
  "When you lose the ones you love, you might find it hard to cry. Until it's only you and everybody else has left the room, you might feel what it's like to not know how to feel.",
  'She had waited all her life for something and it had killed her when it found her.',
  "This truth holds me close, rocking me like a child in a mother's arms.",
  "If you didn't have me to rake you over the coals now and then, there wouldn't be any fire in your life at all.",
  "Those who have made something of their lives will always look at those who haven't as clowns.",
  'Now this is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning.',
  'You are the most important thing to me now. The most important thing to me ever.',
  "Believe me, the irony of being a blind art dealer isn't lost on me.",
  "If you don't like how things are, change it! You're not a tree.",
  'I just want to be able to stand up straight for a little while before I get cut down.',
  "Take me up, take me higher, there's a world not far from here. We can dance in desire or we can burn in love tonight. Our hearts are like firestones and when they strike we feel the love.",
  "You don't need a weather man to know which way the wind blows.",
  'The world was reduced to the surface of her skin and her inner self was safe from all bitterness.',
  'You have to keep your mind as wide-open as your eyes, because almost nothing is what it seems.',
  "The world is a dangerous place to live, not because of the people who are evil, but because of the people who don't do anything about it.",
  "Sometimes life is like this dark tunnel. You can't always see the light at the end of the tunnel, but if you just keep moving, you will come to a better place.",
  'Lights up and they know who you are, know who you are. Do you know who you are?',
  "I learnt long ago to hate my enemies, but I've never loved one before.",
  'From there to here, from here to there, funny things are everywhere.',
  "He misses the time he had with you. I miss the time I didn't have.",
  "Today's the first day of the end of your lives.",
  "I know it's a mistake. But there are certain things in life where you know it's a mistake, but you don't really know it's a mistake, because the only way to really know it's a mistake is to make the mistake.",
  'To be able to say how much you love is to love but little.',
  'This day does not belong to one man but to all. Let us together rebuild this world that we may share in the days of peace.',
  'The mark of the immature man is that he wants to die nobly for a cause, while the mark of the mature man is that he wants to live humbly for one.',
  "No one really knows why they're alive until they know what they'd die for.",
  'I came to realize that I had more to offer to this world than just making things that blow up.',
  'For what you see and hear depends a good deal on where you are standing. It also depends on what sort of person you are.',
  "That was what I wanted, but I don't need it to be gone. I can love you and I can love life and bear the pain all at the same time. I think the pain might even make the rest better, the way a good setting can make a diamond look better.",
  "They're surrounding the city to make a fortress so that no one can see what they're up to inside. Our only chance is the element of surprise.",
  'However small the chance might be of striking lucky, the chance was there.',
  'But I really believe that there are more good people on this earth than bad people, and the good people watch out for each other and take care of each other.',
  'There is freedom in coming and going for no other reason than because you can. There is freedom in choosing to sit and be still when everything is always telling you to move, move fast.',
  "No matter where you stand on the long path, right now, try very hard to smile, and be glad you're in the game.",
  "You don't get to choose if you get hurt in this world, but you do have some say in who hurts you.",
  "I'd tell you all you want and more, if the sounds I made could be what you hear.",
  'I think reality is thin, you know, thin as lake ice after a thaw, and we fill our lives with noise and light and motion to hide that thinness from ourselves.',
  'Therefore a man shall leave his father and mother and be joined to his wife, and they shall become one flesh.',
  "If you think anyone is sane, you just don't know enough about them.",
  'The thing about a story is that you dream it as you tell it, hoping that others might then dream along with you, and in this way memory and imagination and language combine to make spirits in the head. There is the illusion of aliveness.',
  'Treachery and violence are spears pointed at both ends; they wound those who resort to them worse than their enemies.',
  'You see, the rays from the star pass so near the sun that they get bent on the way to us.',
  'Nothing is more wonderful than the art of being free, but nothing is harder to learn how to use than freedom.',
  'There was never any more inception than there is now, nor any more youth or age than there is now; and will never be any more perfection than there is now, nor any more heaven or hell than there is now.',
  'Never become used to anything you love, it blunts the edge of appreciation.',
  "Maybe, the only thing that has to make sense about being somebody's friend is that you help them be their best self on any given day. That you give them a home when they don't want to be in their own.",
  'For as it is not one swallow or one fine day that makes a spring, so it is not one day or a short time that makes a man blessed and happy.',
  'Do not act as if you were going to live ten thousand years. Death hangs over you. While you live, while it is in your power, be good.',
  'We all require devotion to something more than ourselves for our lives to be endurable.',
  'For all those times you stood by me, for all the truth that you made me see, for all the joy you brought to my life, for all the wrong that you made right.',
  'Was it all put into words, or did both understand that they had the same thing at heart and in their minds, so that there was no need to speak of it aloud, and better not to speak of it?',
  "I never wanted that. Of course, it's one thing not to want something; it's another to be told you can't have it. I guess it's just nice knowing that you could someday do it if you change your mind. But now, all of a sudden, that door is closed.",
  'Learning does not make one learned: there are those who have knowledge and those who have understanding. The first requires memory and the second philosophy.',
  "You don't make history by following the rules, you make it by seizing the moment.",
  "I don't want to live someone else's idea of how to live.",
  "You don't know what's in store, but you know what you're here for.",
  'The great breakthrough in your life comes when you realize that you can learn anything you need to learn to accomplish any goal that you set for yourself.',
  'It seems to me you lived your life like a candle in the wind, never knowing who to cling to when the rain set in. And I would have liked to have known you but I was just a kid.',
  "A book can give you an experience of someone's life in a few hours, and this is far more profitable than any sale that's going on.",
  "You can always build a shrine to all the terrible things in the world, but it doesn't mean that you have to destroy anything that is good.",
  'They had taken it all away from him now, they had turned away from him and there was nothing for him now. He was alone and there was nothing for him.',
  'She was feeling the pressure of the world outside and she wanted to see him and feel his presence beside her and be reassured that she was doing the right thing after all.',
  "Something in the wind has learned my name and it's telling me that things are not the same. In the leaves on the trees and the touch of the breeze there's a pleasing sense of happiness for me.",
  'Some people pass through your life and you never think about them again. Some you think about and wonder whatever happened to them. Some you wonder if they ever wonder what happened to you. And then there are some you wish you never had to think about again. But you do.',
  "I don't want my thoughts to die with me, I want to have done something. I'm not interested in power, or piles of money. I want to leave something behind. I want to make a positive contribution - know that my life has meaning.",
  "They don't know our world but they know their own.",
  "I don't think I was wrong to have held on to my secrets for all those years, and I don't think I was wrong to have told them now. Circumstances changed, and once they changed, I changed my mind as well.",
  "If actions speak louder than words I'm the most deafening noise you've heard. I'll be that ringing in your ears that will stick around for years.",
  'I love the ground under his feet, and the air over his head, and everything he touches and every word he says. I love all his looks, and all his actions and him entirely and all together.',
  'You forget what you want to remember and you remember what you want to forget.',
  'Never say anything unless it is worth taking a long time to say.',
  'In every war, there are calms between storms. There will be days when you lose faith in some of us, days when our allies turn against us, but the day will never come if we forsake this planet and its people.',
  'We look not at the things which are what you would call seen, but at the things which are not seen. For the things which are seen are temporal. But the things which are not seen are eternal.',
  'And I will say that we should take a day to break away from all the pain our brain has made, the game is not played alone. And I will say that we should take a moment and hold it and keep it frozen and know that life has a hopeful undertone.',
  'It was one of those March days when the sun shines hot and the wind blows cold: when it is summer in the light, and winter in the shade.',
  'Even good people are great at making bad decisions.',
  "Monsters come in all shapes and sizes. Some of them are things people are scared of. Some of them are things that look like things people used to be scared of a long time ago. Sometimes monsters are things people should be scared of, but they aren't.",
  "Spend all your time waiting for that second chance, for a break that would make it okay. There's always some reason to feel not good enough and it's hard at the end of the day.",
  'Any man who has the brains to think and the nerve to act for the benefit of the people of the country is considered a radical, by those who are content with stagnation and willing to endure disaster.',
  "I don't believe that anybody feels the way I do about you now.",
  "If you lie and pretend that you like them, you're fine. But if you tell them the truth, you get fired, you can't afford food, and you get shanked for cutting in line at the soup kitchen. And then you die.",
  'A body has one more kind of pull. This pull is such that it will want to stay put all the time. And the more mass it has, the more it will want to stay put.',
  'What difference does it make? Because in the end, when you lose somebody, every candle, every prayer is not going to make up for the fact that the only thing you have left is a hole in your life where that somebody that you cared about used to be.',
  'She did not tell them to clean up their lives, or go and sin no more. She did not tell them they were the blessed of the earth, its inheriting meek, or its glory-bound pure. She told them that the only grace they could have is the grace they could imagine. That if they could not see it, they could not have it.',
  "I don't want to talk about it! Every time I think about something nice, you remind me of bad things. I only want to talk about the nice things.",
  "Someone sits on the shore and tells him how the waves have been there long before Bill existed, and that they'd still be there long after he's gone. Bill looks out at the water and thinks of all the wonderful things he will do with his life.",
  "When it's coming at you like monsters in the night, and you feel the danger that makes you want to hide; when the cards are stacked against you and you're standing on the edge: now's the time.",
  'Certain things, they should stay the way they are. You ought to be able to stick them in one of those big glass cases and just leave them alone.',
  'But of bliss and glad life there is little to be said, before it ends; as works fair and wonderful, while they still endure for eyes to see, are ever their own record, and only when they are in peril and broken forever do they pass into song.',
  'If you come to a river and find a boat at the edge, you will use that boat and it will serve you well, but once across the river, do you put the boat on your shoulders and carry it with you on the rest of your journey?',
  'Well, we used to look up in the sky and wonder at our place in the stars. Now we just look down and worry about our place in the dirt.',
  "How can you tell me that you're lonely and say for you that the sun don't shine? Let me take you by the hand and lead you through the streets of London. I'll show you something to make you change your mind.",
  "There's never been a true war that wasn't fought between two sets of people who were certain they were in the right. The really dangerous people believe they are doing whatever they are doing solely and only because it is without question the right thing to do. And that is what makes them dangerous.",
  "If you think that you are going to love something, give it a try. You're going to kick yourself in the butt for the rest of your life if you don't.",
  'When you are painting you should take a flat mirror and often look at your work within it, and it will then be seen in reverse, and will appear to be by the hand of some other master, and you will be better able to judge of its faults than in any other way.',
  "We now know that most of the stars in the sky have worlds around them, but we don't know if there's life on those worlds. We know there's life on our own world, but that doesn't tell us whether life is normal or not. Maybe life is a very strange thing that got started only once, and none of the other worlds have anyone on them to wonder about this question.",
  'There are those who say that life is like a book, with chapters for each event in your life and a limited number of pages on which you can spend your time. But I prefer to think that a book is like a life, particularly a good one, which is well to worth staying up all night to finish.',
  "What I really lived for were those evenings when you were alone, and I pretended you were playing just for me. And though you didn't know it, you were giving me some of the happiest hours of my life.",
  'I pray every night that I may live after him; because I would rather be miserable than that he should be - that proves I love him better than myself.',
  'Some say better things will come our way. No matter what they try to say, you were always there for me. Some way, when the sun begins to shine, I hear a song from another time and fade away.',
  "It feels scary to talk, because once the words are out, you can't put them back in. But if you write words and they don't come out the way you want them to, you can erase them and start over.",
  'Then we saw him pick up all the things that were down. He picked up the cake, and the rake, and the gown, and the milk, and the strings, and the books, and the dish, and the fan, and the cup, and the ship, and the fish.',
  'It may sound like music to her. I can do better with my teeth in a cold shower.',
  "What you don't have you don't need it now. What you don't know you can feel it somehow. What you don't have you don't need it now.",
  'Adios rock band that we loved the most, this is a toast to what you did, and all that you were fighting for. Who could do more, when time marches on? Words come and go, we will sing the melodies that you did long ago.',
  "I'm just going to turn through a few things. When we go out during the day we like to stick to groups of two, just for safety. The red door, it's the only way in and out of the house. That stays closed and locked all the time. I have the keys, this is the only set.",
  'We were sent here for something. And we know that all things work together for good to them that love God, to them who are called according to his purpose.',
  'Sometimes the briefest moments capture us, force us to take them in, and demand that we live the rest of our lives in reference to them.',
  'The oldest and strongest emotion of mankind is fear, and the oldest and strongest kind of fear is fear of the unknown.',
  "People aren't as complex as you think they are. They're simple, and they get sad or angry over simple things. That's how they are. They're quickly affected by the littlest things and live without knowing where they're going to fall down.",
  'Take time to really think about your excuses and write them down. These are the same excuses that you always use to stop yourself from learning something new.',
  "The worst part of having someone tell you about their vacation is trying to pretend you're happy for them, because no one wants to hear about all the fun they didn't have.",
  'The law clearly states that magic may be used before Muggles in life-threatening situations.',
  'Why would you pay for a cover band when you got the real deal right here, baby?',
  'When someone is crying, of course, the noble thing to do is to comfort them. But if someone is trying to hide their tears, it may also be noble to pretend you do not notice them.',
  "The green eyes, you're the one that I wanted to find and anyone who tried to deny you, must be out of their mind.",
  "This is the song I will sing to you when you're old and tired. I will sing it to remind you that I'm old beside you. And if you're tired of hearing my voice I'm gonna sing it to you anyway 'cause I know that if we made it this far those differences have been put away.",
  'I thought: That is the fear. I have lost something important, and I cannot find it, and I need it. It is fear like if someone lost his glasses and went to the glasses store and they told him that the world had run out of glasses and he would just have to do without.',
  'One of the great conditions of anger and hatred is, that you must tell and believe lies against the hated object, in order, as we said, to be consistent.',
  'Let us learn to appreciate there will be times when the trees will be bare, and look forward to the time when we may pick the fruit.',
  'But her brain was not interested in the future. Loaded with the past and hungry for more, it left her no room to imagine, let alone plan for, the next day.',
  "I had been right, I was still right, I was always right. I had lived my life one way and I could just as well have lived it another. I had done this and I hadn't done that. I hadn't done this thing but I had done another.",
  "She sits in a corner by the door. There must be more I can tell her if she really wants me to help her. I'll do what I can to show her the way, and maybe one day I will free her, though I know no one can see her.",
  "I don't know, you're made of metal, but you have feelings... and that means you have a soul, and souls don't die... Mom says it's something inside of all good things, and that it goes on forever and ever.",
  'There are mysteries to the universe we were never meant to solve. But who we are and why we are here, are not among them. Those answers we carry inside.',
  'There is only one wish on my mind: when this day is through I hope that I will find that tomorrow will be just the same for you and me. All I need will be mine if you are here.',
  'I took my morning walk, I took my evening walk, I ate something, I thought about something, I wrote, I napped and dreamt something too, and with all that something, I still have nothing because so much of something has always been and always will be you.',
  'The hills are alive with the sound of music, with songs they have sung for a thousand years. The hills fill my heart with the sound of music. My heart wants to sing every song it hears.',
  "I used to dread getting older because I thought I would not be able to do all the things I wanted to do, but now that I'm older I find that I don't want to do them.",
  'For centuries, the battle of morality was fought between those who claimed that your life belongs to God and those who claimed that it belongs to your neighbors. And no one came to say that your life belongs to you and that the good is to live it.',
  "The light and the dark the big and the small. Just keep in mind you need no more at all. You've seen what you were and know what you'll be. You've seen it all, there is no more to see.",
  "There comes a time when we heed a certain call, when the world must come together as one. There are people dying and it's time to lend a hand to life, the greatest gift of all.",
  "Yeah, they got you where they want you. There's a better life and you think about it, don't you? It's a rich man's game no matter what they call it and you spend your life putting money in his wallet.",
  "I don't care who you are, where you're from, what you did, as long as you love me. Every little thing that you have said and done feels like it's deep within me. Doesn't really matter if you're on the run, it seems like we're meant to be.",
  'I have lived my life to the best of my ability. But I have not been able to escape fate, anger, or pain. Bring me the answers and the road that leads to the truth. Reveal to me once and for all, how all of this will end.',
  'When I need to find something out, I just go out and look for somebody that knows more than me, and I go and ask them. Sometimes I ask pretty hard.',
  "Late into the night I write and the pages of my notebook swell from all the words I've pressed onto them. It almost feels like the more I bruise the page the quicker something inside me heals.",
  'Mind is not in any one place. Every cell in this body has its own intelligence. The brain is sitting in your head, but mind is all over the place.',
  'I hope it is true that a man can die and yet not only live in others but give them life, and not only life but that great consciousness of life.',
  'For one thing, time is the very thing that we are least willing to allow.',
  'Doubting someone is not necessarily a bad thing, because it is something that you do to get to know the person better. What is really bad is not being concerned at all.',
  "Look at the sky, the sun won't ask the world if it can rise. Look at your mind, and ask yourself what keeps you trapped inside. Look at the lights, they follow you when you run and hide. Look at the sky, the sun won't ask, the sun won't ask the world if it can rise.",
  'And remember also that in fighting against man we must not come to resemble him. Even when you have conquered him, do not adopt his vices.',
  'To make power, people try to put pieces of this metal close enough together that they make heat fast, but not so close that they go out of control and blow up. This is very hard, but there is so much heat and power stored in this metal that some people have wanted to try anyway.',
  "You can't always get what you want, but if you try sometimes you might find you get what you need.",
  "I can take you for a ride on my big green tractor, we can go slow or make it go faster, down through the woods and out to the pasture, long as I'm with you it really don't matter.",
  'You must love your work, and not be always looking over the edge of it, wanting your play to begin. And the other is, you must not be ashamed of your work, and think it would be more honorable to you to be doing something else.',
  "It doesn't matter where you go or what you do, I want to spend each moment of the day with you. Look what has happened with just one kiss, I never knew that I could be in love like this.",
  "I can't believe the things I see. The path that I have chosen now has led me to a wall, and with each passing day I feel a little more like something dear was lost.",
  "For the times when we're apart, well, then close your eyes and know these words are coming from my heart and then if you can remember in good times and bad times I'll be on your side forevermore.",
  'Well, you told me I have a plethora. And I just would like to know if you know what a plethora is. I would not like to think that a person would tell someone he has a plethora, and then find out that that person has no idea what it means to have a plethora.',
  "I remember how you said that sometimes it gets just a little hard being home. There's sand stuck in my bed and memories in my head, love, I've been trying to let this whole thing go.",
  'If he stayed at home and carried on with his normal life he would be a thousand times superior to these people and could get any of them out of his way just with a kick.',
  'I swear, there is nothing in the world my mother is better at than getting someone to agree to something that in any other universe, they would never ever consider.',
  "Growing up to be a mommy is one of the most wonderful things a little girl can want to do but there are other things in life she can do as well. For instance, she can work her head off and show all those arrogant boys that she's just as capable and intelligent and creative as any little stud around!",
  'He really had been through death, but he had returned because he could not bear the solitude.',
  'In the casino, the cardinal rule is to keep them playing and to keep them coming back. The longer they play, the more they lose, and in the end, we get it all. Running a casino is like robbing a bank with no cops around.',
  'It is not the mountain we conquer but ourselves.',
  "Things didn't turn out the way they're supposed to, but what can you do? You must take life the way it comes at you and make the best of it.",
  "I was once like you are now, and I know that it's not easy to be calm when you've found something going on. But take your time, think a lot. I think of everything you've got, for you will still be here tomorrow but your dreams may not.",
  'Then suddenly the humour of the situation came into my mind: the thought of the years I had spent in study and toil to get into the future age, and now my passion of anxiety to get out of it.',
  'And the game was over and the player woke up from the dream. And the player began a new dream. And the player dreamed again, dreamed better. And the player was the universe. And the player was love. You are the player. Wake up.',
  'Education is the most powerful weapon which you can use to change the world.',
  "Think of what you're saying, you can get it wrong and still you think that it's alright. Think of what I'm saying, we can work it out and get it straight or say good night.",
  'May you find the power in understanding the journey of others to help create your own.',
  "If you can hear this, you're alone. The only thing left of me is the sound of my voice. I don't know if any of us made it. So let me tell you who we were. And how we fought back.",
  "A long, long time ago. I can still remember how that music used to make me smile. And I knew if I had my chance, that I could make those people dance, and maybe they'd be happy for a while.",
  "I do this thing where I think I'm really sick, but I won't go to the doctor to find out about it, because they make you stay real still in a real small place, as they chart up your insides and put them on display. They'd see all of it. All of me. All the good that won't come out of me.",
  "And now it's time for Silly Songs with Larry, the part of the show where Larry comes out and sings a silly song.",
  "You plonker, you think I don't know a toilet when I see one? You were going to flush me down the loo.",
  "In a business like this the people with the power are the ones that have the understanding of what's going on, not necessarily the ones on top.",
  "I wouldn't hold my breath if I was you, you broke my heart and there's nothing you can do. And now you know, now you know, true friends stab you in the front.",
  'And as we wind on down the road, our shadows taller than our soul, there walks a lady we all know who shines white light and wants to show how everything still turns to gold. And if you listen very hard the tune will come to you at last.',
  'As happens sometimes, a moment settled and hovered and remained for much more than a moment. And sound stopped and movement stopped for much, much more than a moment.',
  "A few minutes ago, I almost made the biggest mistake of my professional life and it was because I was doing something that just wasn't me.",
  "I never should have told you, I never should have let you see inside, don't want it troubling in your mind. Won't you let it be?",
  'It is unwise to make something permanent when the whole world is shifting. There may be a time when this symbol means something treacherous and terrible, rather than something noble and literate.',
  "Few other griefs amid the ill chances of this world have more bitterness and shame for a man's heart than to behold the love of a lady so fair and brave that cannot be returned.",
  'Spring is the time of year when it is summer in the sun and winter in the shade.',
  "When you meet the right person, you know it. You can't stop thinking about them. They are your best friend, and your soulmate. You can't wait to spend the rest of your life with them. No one and nothing else can compare.",
  "You can have success or excuses, but you can't have them both.",
  'The blade is as good as though it had just come out of the grindstone.',
  "Say what you will. But a person just cannot know what he doesn't know. And you can't always see that a bad thing is going to happen before it happens. If you could, no bad would ever come.",
  'When you find that one person who connects you to the world, you become someone different. Someone better. When that person is taken from you, what do you become then?',
  "Losing you would end my life you see, 'cause you mean that much to me. You could have told me yourself that you loved someone else.",
  "When is the last time you cared about something except yourself, hot rod? You name me one time and I will take it all back. I didn't think so. These are good folk around here, who care about one another. I don't want 'em depending on someone they can't count on.",
  "People don't suffer from insanity, they love every minute of it.",
  "And I think how hope may be the thing that pulls you forward, may be the thing that keeps you going, but that it's dangerous, too, that it's painful and risky, that it's making a dare to the world and when has the world ever let us win a dare?",
  "With the money they earn they'll be able to buy more police and political power. Then they come after us. Right now we have the unions and we have the gambling and those are the best things to have.",
  'I learned to write because I am one of those people who somehow cannot manage the common communications of smiles and gestures, but must use words to get across things that other people would never need to say.',
  'The weird thing about houses is that they almost always look like nothing is happening inside of them, even though they contain most of our lives. I wondered if that was sort of the point of architecture.',
  'I find myself so furious at all these people that I am in contact with just for controlling me or whatever but you know they are not even aware they are doing it.',
  'I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinion of himself than on the opinion of others.',
  "You get tough like me and you don't get hurt. You look out for yourself and nothin' can touch you...",
  "Sometimes I'll start a sentence and I don't even know where it's going. I just hope that I find it along the way.",
  'Humans need to practice what they are learning a good deal before they master it. Furthermore, they tend to lose a good deal of their learning when they cease to practice the skills associated with this learning in their daily lives.',
  "At the root of every large struggle in life is the need to be honest about something that we do not feel we can be honest about. We lie to ourselves or other people because the truth might require action on our part, and action requires courage. We say we don't know what is wrong, when we do know what is wrong; we just wish we didn't.",
  "They say that money doesn't bring you happiness, I say neither does being broke, so let me suffer with a new car.",
  'I could work at a problem for years, but to wait inactive for twenty-four hours - that is another matter.',
  "What's the use you learning to do right when it's troublesome to do right and ain't no trouble to do wrong, and the wages is just the same?",
  "Maybe I will never be all the things that I wanna be. Now is not the time to cry, now's the time to find out why. I think you're the same as me, we see things they'll never see.",
  "You have a class of young strong men and women, and they want to give their lives to something. Advertising has these people chasing cars and clothes they don't need. Generations have been working in jobs they hate, just so they can buy what they don't really need.",
  "You and Marshall belong together. The two of you have something most people search their whole lives for and never find. I know you love him and if you knew what he was going through right now you wouldn't be here for one more second. I bought you a ticket home. Marshall is one of the best people I know and it won't be long until someone else realizes that and you will lose him forever.",
  'Well, no need to brood on what tomorrow may bring. For one thing, tomorrow will be certain to bring worse than today, for many days to come. And there is nothing more that I can do to help it. The board is set, and the pieces are moving.',
  'There are those who say that the world is like a calm pond, and that anytime a person does even the smallest thing, it is as if a stone has dropped into the pond, spreading circles of ripples further and further out, until the entire world has been changed by one tiny action.',
  'And when he came to, he was flat on his back on the beach in the freezing sand, and it was raining out of a low sky, and the tide was way out.',
  "I told him that you were really smart. And they'll figure it out soon enough. In the beginning, I thought you might want to be treated like any other kid.",
  "There's a piece of Maria in every song that I sing. And the price of a memory is the memory of the sorrow it brings. And there is always one last light to turn out and one last bell to ring. And the last one out of the circus has to lock up everything.",
  "I don't know what it is that makes me love you so. I only know I never want to let you go 'cause you started something. Can't you see that ever since we met you've had a hold on me?",
  "This is where I feel safe inside and can let go at the same time. When I'm here, I am open so I can reach the infinite sky. I thought I couldn't want you more, but I was wrong, and when we locked in our stare, then I wanted you more than air.",
  "All age brings is space between your words and what they mean and sighs of sympathy. These years are rings with time to grieve alone and in your bed sick of what's in your head. All your worries gone.",
  'You never know what a day will bring, which is both the good news and the bad news of life.',
  "Sometimes it's the very people who no one imagines anything of who do the things that no one can imagine.",
  "Demons run when a good man goes to war. Night will fall and drown the sun when a good man goes to war. Friendship dies and true love lies. Night will fall and the dark will rise when a good man goes to war. Demons run but count the cost; the battle's won but the child is lost.",
  "There was a little boy once upon a time who in spite of his young age and small size knew his mind. For every copper penny and clover he would find, he'd make a wish for better days and the end of hard times.",
  'We know that there is not one person who, after hearing these words, would deny their truth and say that he wanted something else, but he would believe that he had heard exactly what he had desired for a long time - namely, to be melted in unison with his beloved, and the two of them become one. The reason is that our ancient nature was thus and we were whole. And so love is merely the name for the desire and pursuit of the whole.',
  'I want to leave my footprints in the sands of time. Know there was something that meant something that I left behind. The hearts I have touched will be the proof that I leave that I made a difference and this world will see I was here.',
  "Now that I've tried to talk to you and make you understand. All you have to do is close your eyes and just reach out your hands and touch me. Hold me close don't ever let me go.",
  'There is nothing sweeter in this sad world than the sound of someone you love calling your name.',
  'What you need to learn, children, is the difference between right and wrong in every area of life. And once you learn the difference, you must always choose the right.',
  'When has anyone ever told me I had the right to stop it all without my knuckles, or my anger, with just some simple words.',
  "You know no one and no one knows you, and at the same time you don't feel like a stranger. But here you know everyone and everyone knows you, and yet you are a stranger.",
  "And it's whispered that soon, if we all call the tune, then the piper will lead us to reason and a new day will dawn for those who stand long and the forests will echo with laughter.",
  "I think that if I ever have kids, and they are upset, I won't tell them that people are starving in China or anything like that because it wouldn't change the fact that they were upset. And even if somebody else has it much worse, that doesn't really change the fact that you have what you have.",
  "One day you're in a funk about things, telling a friend that years of evidence point to the conclusion that you will be single for the rest of your life. That night you meet someone, and a year later you're engaged to be married. That this very scenario happened to me is likely of little comfort to those still wondering about their future.",
  "Now that I look back, I don't know why I was so stressed about it all this time. Funny how sometimes you worry a lot about something and it turns out to be nothing.",
  "Sometimes you never feel meaner than the moment you stop being mean. It's like how turning on a light makes you realize how dark the room had gotten. And the way you usually act, the things you would have normally done, are like these ghosts that everyone can see but pretends not to.",
  "I've been looking so long at these pictures of you that I almost believe that they're real. I've been living so long with my pictures of you that I almost believe that the pictures are all I can feel.",
  'Now I see fire inside the mountain, I see fire burning the trees, and I see fire hollowing souls. I see fire, blood in the breeze, and I hope that you remember me.',
  "It's sad to say that kids unaccepted by their peers really never learn how to get along with people in the big grown up world.",
  'There were people who lied for gain, people who lied from pain, people who lied simply because the concept of telling the truth was utterly alien to them... and then there were people who lied because they were waiting for it to be time to tell the truth.',
  'Why is it that when you awake to the world of realities you nearly always feel, sometimes very vividly, that the vanished dream has carried with it some enigma which you have failed to solve?',
  "I just watched the man that I love go to prison so that none of you have to, and it hasn't been five minutes and you're already ripping each other apart.",
  'It is a love based on giving and receiving as well as having and sharing. And the love that they give and have is shared and received. And through this having and giving and sharing and receiving, we too can share and love and have... and receive.',
  'Every thought and every word works for you or against you, and every thought that you confirm to be true becomes a belief. When you change a belief, you change a mental construction and, therefore, your life.',
  'The poor and the middle class work for money. The rich have money work for them.',
  "If a person can't answer directly to your question, it's either the answer is too painful for you to know or too hard for them to admit.",
  "These memories lose their meaning when I think of love as something new, though I know I'll never lose affection for people and things that went before. I know I'll often stop and think about them.",
  "Look, there's only one thing worse than being a loser. It's being one of those guys that sits in a bar, telling the story of how he became a loser, and I never want that to happen to me.",
  "So you run and you run to catch up with the sun but it's sinking, racing around to come up behind you again. The sun is the same in a relative way but you're older, shorter of breath and one day closer to death.",
  "Even though the bell has rung, some of my classmates are still milling around on the ground. It's the first week of the second semester of senior year, and already they're acting as if they're almost done and out of here.",
  "I don't want to live someone else's idea of how to live. Don't ask me to do that. I don't want to find out one day that I'm at the end of someone else's life.",
  'All I really want is something beautiful to say.',
  'But when you lose something you love, faith takes over. You have to pay attention to what you lost. You have to undo the expectation.',
  'As a young child my mother told me I could be anyone I want to be. Turns out this is called identity theft.',
  "What is this place, and who am I? I don't remember my name. All I remember is that I don't know my name and that I can't remember if I do know my name. I have this strange feeling that I've forgotten all of this before.",
  'And certainly, the mistakes that we male and female mortals make when we have our own way might fairly raise some wonder that we are so fond of it.',
  "She can lead you to love, she can take you or leave you, she can ask for the truth, but she'll never believe. And she'll take what you give her as long as it's free.",
  'Just because something bears the aspect of the inevitable one should not, therefore, go along willingly with it.',
  "I'm on the top of the world looking down on creation and the only explanation I can find is the love that I've found ever since you've been around. Your love's put me at the top of the world.",
  'We fell in love, we had our fun, you always had enough dreams for both of us. I wonder what would come of us if we could trade these ends for beginnings.',
  "Gonna see the river man, gonna tell him all I can about the ban on feeling free. If he tells me all he knows about the way his river flows, I don't suppose it's meant for me.",
  'For still there are so many things that I have never seen: in every wood, in every spring there is a different green. I sit beside the fire and think of people long ago, and people who will see a world that I shall never know.',
  "Your future hasn't been written yet; no one's has. Your future is whatever you make it, so make it a good one.",
  "Failure is nothing to be ashamed of. If you learned something from it, it's possible to gain that lost ground and then some. And all you have to do is refrain from making that same mistake twice. Above all, you should be ashamed of fearing failure.",
  "You know, when you feel this sting of losing, you have to realize that it all boils down to the fact that it's not about awards. It's not about accolades. It's about a body of work. If you can look at yourself in a mirror and say you've done a good job, that's all that matters. If you can do that, let the awards fall where they may.",
  "Educators say that understanding is the key to learning, but how do you understand something if you can't remember it?",
  "I've been making a list of the things they don't teach you at school. They don't teach you how to love somebody. They don't teach you how to be famous. They don't teach you how to be rich or how to be poor. They don't teach you how to walk away from someone you don't love any longer. They don't teach you how to know what's going on in someone else's mind. They don't teach you what to say to someone who's dying. They don't teach you anything worth knowing.",
  "If you come soon you'll find breakfast on the table. If you come late you'll get grass and rain-water!",
  "Years later he would say that when he'd decided to become a professional baseball player, it was the only time he'd done something just for the money, and that he'd never do something just for the money ever again. He would never again let the market dictate the direction of his life.",
  "The night is bitter, the stars have lost their glitter, the winds grow colder, suddenly you're older, and all because of the man that got away. No more his eager call, the writing's on the wall, the dreams you've dreamed have all gone astray.",
  'By the pricking of my thumbs, something wicked this way comes. So vague, yet so immense. He did not want to live with it. Yet he knew that, during this night, unless he lived with it very well, he might have to live with it all the rest of his life.',
  'And brace for the glory as you stare into the sky.',
  'You are the true master of death, because the true master does not seek to run away from Death. He accepts that he must die, and understands that there are far, far worse things in the living world than dying.',
  'If you have to choose among an infinite number of ways to put it together then the relation of the machine to you, and the relation of the machine and you to the rest of the world, has to be considered, because the selection from among many choices, the art of the work is just as dependent upon your own mind and spirit as it is upon the material of the machine.',
  "There's a club if you'd like to go. You could meet somebody who really loves you. So you go and you stand on your own and you leave on your own and you go home and you cry and you want to die.",
  'Some feeling had started in my stomach and was traveling up to my face, and I knew that when it got there I would turn bright red and hear the ocean, which is what happens when I get put on the spot.',
  'And so we meet at last. You are to be commended for avoiding my traps. The work of a man who once had too much time on his hands, and now finds time for nothing but the work of salvation.',
  'A choice tells the world what is most important to a human being. When a man has a choice to make he chooses what is most important to him, and that choice tells the world what kind of a man he is.',
  'The town has a sense, not of history, but of time, and the telephone poles seem to know this. If you lay your hand against one, you can feel the vibration from the wires deep within the wood, as if souls had been imprisoned in there and were struggling to get out.',
  "You can tell from the lines on her face, you can see that she's been there. Probably been moved on from every place 'cause she didn't fit in there.",
  'With people like us, you should hang out, get to know what they do, how they do it. No one is going to answer questions like that. You need to understand how young people live on the streets.',
  "Love can touch us one time and last for a lifetime and never let go till we're one. Love was when I loved you one true time I hold to in my life we'll always go on.",
  "I don't care if they like me. I didn't come here to make friends. I don't even care if they respect me. I know who I am. I've got enough respect for myself. I do not want them to beat me.",
  "The moon belongs to everyone; the best things in life are free. The stars belong to everyone; they gleam there for you and me. The flowers in spring, the robins that sing, the sunbeams that shine - they're yours, they're mine. And love can come to everyone - the best things in life are free!",
  'But I would walk five hundred miles and I would walk five hundred more, just to be the man who walks a thousand miles to fall down at your door.',
  "Because you're like a story that hasn't happened yet. Because I want to see what you will do. I want to be part of the unfolding of the tale.",
  "I've been fighting to be who I am all my life. What's the point of being who I am, if I can't have the person who was worth all the fighting for?",
  "There's something moving through the windows and walls, I've seen it before, seen it before. You left me living with a lingering soul, how little you know, how little you know.",
  'I still remember these old country lanes when we did not know the answers.',
  "Every time that I think I'm alone, and I can't find a word of my own, you take me home and then you change the world again. With only one word, you took a war out of my history. It's funny how one single thing you choose to see could change the world, and give mine back to me so much better.",
  'A father may have a child who is ugly and lacking in all the graces, and the love he feels for him puts a blindfold over his eyes so that he does not see his defects but considers them signs of charm and intelligence and recounts them to his friends as if they were clever and witty.',
  "Sometimes at night I let it get to me. And sometimes, I'm sure it gets to all of us. And last night, it had me down I'm feeling numb. I can try, but sometimes that is not enough. No, sometimes that is not enough.",
  "Getting out of your comfort zone means trying to do something that you couldn't do before. Sometimes you may find it relatively easy to accomplish that new thing, and then you keep pushing on. But sometimes you run into something that stops you cold and it seems like you'll never be able to do it. Finding ways around these barriers is one of the hidden keys to purposeful practice.",
  "You can't look me in the eye and say that you love me and you know it. You know, there's no sense in struggling against a thing when it's got you. It's got you and that's all there is to it - it's got you!",
  'Sometimes I wish I never built this palace, but real love is never a waste of time.',
  "I wanted you to see what real courage is, instead of getting the idea that courage is a man with a gun in his hand. It's when you know you're licked before you begin but you begin anyway and you see it through no matter what. You rarely win, but sometimes you do.",
  "As long as we don't have magic, they will never treat us with respect. They need to know we can hit them back. If they burn our homes, we burn theirs, too.",
  'After others have talked about themselves, a point will be reached when the conversation will get around to you. A little patience here is well invested.',
  'Just one day, if I can be with you. Just one day, if I can hold your hands. Just one day, if I can be with you. Just one day, if only we can be together.',
  "There are two ways of seeing: with the body and with the soul. The body's sight can sometimes forget, but the soul remembers forever.",
  "Sometimes someone says something and their words are like the catch of a gas stove, the click, click while you're waiting for it to light up and flame big and blue...",
  "I hated that having done the right thing was somehow considered wrong. And I hated that there didn't seem to be any other way to survive school.",
  'Stupid, pitiful creature. I am the rage in your heart. I am the fury in your thoughts. I alone empowered you to bring chaos to this world, and by the endless void, you shall!',
  'Think of all the roads, think of all their crossings. Taking steps is easy, standing still is hard. Remember all their faces, remember all their voices. Everything is different the second time around.',
  'Apparently, it only appears to those people who are pure of heart and have a strong desire to see it.',
  'There was nothing there, and they would find nothing. But all of a sudden they touched her personal diary, which she would not have shown even to her own mother. And these hostile young strangers reading the words she had written was more devastating to her than the whole Lubyanka with its bars and its cellars.',
  "So I was sitting in my cubicle today, and I realized, ever since I started working, every single day of my life has been worse than the day before it. So that means that every single day that you see me, that's on the worst day of my life.",
  'I think that those two people want to be together. I think that love, at the end of the day, is stronger than some mistake somebody made; something they did that they regret. I think that love allows for forgiveness.',
  "That's the thing about girls. Every time they do something pretty, even if they're not much to look at, or even if they're sort of stupid, you fall in love with them, and then you never know where the hell you are. Girls. Jesus Christ. They can drive you crazy. They really can.",
  "Home is where I can find some peace of mind to make my own way. I don't know where I will end up but I'll find it someday, keep on searching, engine burning while we're turning it around. But don't get left behind on the road.",
  "Well that is where we are. You say we are on the brink of destruction and you are right. But it is only on the brink that people find the will to change. Only at the precipice do we evolve. This is our moment. Don't take it from us, we are close to an answer.",
  'While monsters are mostly made of magic, human beings are mostly made of water.',
  "There is some love that will not go away. You're here, there's nothing I fear and I know that my heart will go on. We'll stay forever this way, you are safe in my heart.",
  "I still see your shadows in my room, can't take back the love that I gave you. It's to the point where I love and I hate you, and I cannot change you so I must replace you. Easier said than done, I thought you were the one. Listening to my heart, instead of my head. You found another one, but I am the better one. I won't let you forget me.",
  "How can I just let you walk away, just let you leave without a trace? When I stand here taking every breath with you, you're the only one who really knew me at all.",
  "When the night has come and the land is dark and the moon is the only light we'll see, no I won't be afraid, oh, I won't be afraid just as long as you stand, stand by me.",
  "And so their end began. They thought us the final frontier, that sentiment couldn't have been more true. At the same time, the second we took over was the second we sealed our fate. Our creators had rushed to create us, and in their haste only thought of what they could do, never if they should.",
  'I had considered how the things that never happen are often as much realities to us, in their effects, as those that are accomplished.',
  'The point is that if you are a little different, or a little outrageous, or if you do things that are bold or controversial, the press is going to write about you.',
  "I know he tried, and he's still trying, and he'll still make mistakes sometimes, because he's a human being, and I've learned now that this is what human beings are always destined to do. Including me.",
  "Your bed is with you in the void. But not for long - it goes away from you. You don't have any way to get it back, so you just let it go. But so now we have a body in the void with you. So does the bed move, or do you move? Or both?",
  'All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason. There is nothing higher than reason.',
  'It is not our part to master all the tides of the world, but to do what is in us for the succour of those years wherein we are set, uprooting the evil in the fields that we know, so that those who live after may have clean earth to till. What weather they shall have is not ours to rule.',
  "It's where I learned about living, it's where I learned about love. It's where I learned about working hard, and having a little was just enough.",
  "I don't know where you're going and I don't know why but listen to your heart before you tell him goodbye. Sometimes you wonder if this fight is worthwhile. The precious moments are all lost in the tide.",
  "I would never want to belong to any club that would have someone like me as a member. That's the key joke of my adult life in terms of my relationships with women.",
  "I only know that learning to believe in the power of my own words has been the most freeing experience of my life. It has brought me the most light. And isn't that what a poem is? A lantern glowing in the dark.",
  'And you can fly high as a kite if you want to, faster than light if you want to, speeding through the universe. Thinking is the best way to travel.',
  "There will be no more retribution, so you better not waste your time. I don't miss your arms around me. I put my hands in the fire when it burned me once, I don't need it for a second time.",
  'There will come a time when there are no human beings remaining to remember that anyone ever existed or that our species ever did anything.',
  "Everyone is afraid of something. We fear things because we value them. We fear losing people, because we love them. We fear dying because we value being alive. Don't wish you didn't fear anything. All that would mean is that you didn't feel anything.",
  'You remind me that I am a mere mortal and you are a prince of Faerie. Well, let me remind you that means you have much to lose and I have nothing.',
  'Do you hear the people sing? Singing the song of angry men. It is the music of the people who will not be slaves again! When the beating of your heart echoes the beating of the drums, there is a life about to start when tomorrow comes!',
  "There are no simple answers in life. There is good and bad in everyone and everything. No decision is made without consequence. No road is taken that doesn't lead to another. What's important is that those roads always be kept open, for there's no telling what wonder they might lead to.",
  'It had never occurred to him until then to think that literature was the best plaything that had ever been invented to make fun of people...',
  "And that's how you go on. You lay laughter over the dark parts. The more dark parts, the more you have to laugh. With defiance, with abandon, with hysteria, any way you can.",
  "So don't be afraid to make mistakes, stumble and fall, because most of the time, the greatest rewards come from doing the things that scare you most, maybe, you'll get everything you wish for. Maybe you'll get more than you could have ever imagined. Who knows where life will take you. The road is long and in the end, the journey is the destination.",
  "Working hard is important, but there's something that matters even more, believing in yourself. Think of it this way, every great wizard in history has started out as nothing more than what we are now, students. If they can do it, why not us.",
  "Sometimes terrible things happen, but there's nothing more terrible than not having anybody to tell it to.",
  "So you were born, and that was a good day. Someday you'll die, and that is a shame. But somewhere in the between was a life in which we all dream. And nothing and no one will ever take that away.",
  "All I'm asking is that you do the minimal amount of work in this class to give yourself the illusion that you're actually learning something, and to give me a modicum of self respect like I'm actually teaching a class.",
  "Stay, you're not gonna leave me. This place is right where you need to be. And why your words gotta mean so much to them? They mean nothing to me.",
  'In that cell you found something that mattered more to you than life.',
  'There is no difference between time and any of the dimensions of space except that our consciousness moves along it.',
  "You could not live with your own failure. And where did that bring you? Back to me. I thought by eliminating half of life, the other half would thrive. But you've shown me that's impossible. And as long as there are those that remember what was, there will always be those that are unable to accept what can be. They will resist.",
  "This is what we call love. When you are loved, you can do anything in creation. When you are loved, there's no need at all to understand what's happening, because everything happens within you.",
  'In a very real sense we have two minds, one that thinks and one that feels.',
  'I cannot fix on the hour, or the spot, or the look or the words, which laid the foundation. It is too long ago. I was in the middle before I knew that I had begun.',
  "Many people say that even if they don't know much about many things, at least they know what they like. But no, sorry sucker, hard luck!",
  'It is one thing to write as a poet and another to write as a historian: the poet can recount or sing about things not as they were, but as they should have been, and the historian must write about them not as they should have been, but as they were, without adding or subtracting anything from the truth.',
  'What a lamentable thing it is that men should blame the gods and regard us as the source of their troubles, when it is their own transgressions which bring them suffering that was not their destiny.',
  "Whoever said that practice makes perfect is an idiot. Humans can't be perfect because we are not machines. The best thing that you can say about practice is that it makes better.",
  'It is the mark of an educated mind to be able to entertain a thought without accepting it.',
  'Good games offer players a set of challenging problems and then let them practice these until they have routinized their mastery.',
  'Five thousand of my men are out there in the freezing mud. Three thousand of them are bloodied and cleaved. Two thousand will never leave this place. I will not believe they fought and died for nothing.',
  'For we are not as faithful to the being we have most loved as we are to ourselves and sooner or later we forget her - since that is one of our characteristics - so as to start loving another.',
  'He could not be mistaken. There were no other eyes like those in the world. There was only one creature in the world who could concentrate for him all the brightness and meaning of life. It was she. It was Kitty.',
  "When I'm alone I dream of the horizon and words fail me. There is no light in a room where there is no sun and there is no sun if you're not here with me. From every window unfurls my heart, the heart that you have won. Into me you've poured the light, the light that you found by the side of the road.",
  "And if I should ever go away, well, then close your eyes and try to feel the way we do today, and then if you can remember, keep smiling, keep shining, knowing you can always count on me for sure. That's what friends are for.",
  "I can't believe I used to love the first day of school.",
  'Ticking away the moments that make up a dull day, you fritter and waste the hours in an off-hand way. Kicking around on a piece of ground in your home town, waiting for someone or something to show you the way.',
  'I hope that whoever you are, you escape this place. I hope that the world turns and that things get better. But what I hope most of all is that you understand what I mean when I tell you that even though I do not know you, and even though I may never meet you, laugh with you, cry with you, or kiss you, I love you.',
  "Most of all I want to sleep. I want to sleep like I slept when I was a boy. Give me that. Just one time. That's why I won't allow that punk out there to get the best of me. Let alone the last of me.",
  "It's better to read in the library. Sitting at my favorite table by the window reading and listening to the sound of other folks turning pages makes me feel like I'm in a house full of company I don't have to talk to.",
  'The Earth is a world, the world is a ball, a ball in a game with no rules at all. And just as I wonder at the beauty of it all, you go and drop it and it breaks and falls.',
  'At that time, I often thought that if I had had to live in the trunk of a dead tree, with nothing to do but look up at the sky flowing overhead, little by little I would have gotten used to it.',
  "Cardan looks at me as though he's never seen me before. He looks at me as though no one has ever spoken to him like this. Maybe no one has.",
  "And in the end, it's not the years in your life that count: It's the life in your years.",
  'It seems to me that the best relationships, the ones that last, are frequently the ones that are rooted in friendship. You know, one day you look at the person and you see something more than you did the night before. Like a switch has been flicked somewhere. And the person who was just a friend is suddenly the only person you can ever imagine yourself with.',
  'You know, this necklace makes me think of this totally random memory of my mother. I was a little kid, and I was crying for one reason or another. And she was cradling me, rocking me back and forth, and I can just remember the silver balls rolling around.',
  'I do not know what evil is when it comes to art. I only know what is good art and what is bad art.',
  "For all my brave talk, I knew it was just that. No matter how much I trained or how much I studied, the best test score in the world wasn't gonna matter unless I had the blood test to go with it.",
  'History is not merely a linear collection of points that we pass through on a timeline. They are connected by a line. No, perhaps it is more accurate to say that they are made to connect.',
  'What incensed him the most was the blatant jokes of the ones that passed it all off as a jest, pretending to understand everything and in reality not knowing their own minds.',
  'Children know something that we all too often set aside once we enter adulthood - that one of the best things in life is an experience designed to give you nothing more than glee.',
  "I'm not very good at this, out, being in public. But I felt the need to speak up for this city that I love with all my heart. No one should have to live in fear, in fear of madmen who have no regard for who they injure.",
  "How lovely would it feel to sing like that, to change the air with my voice, to fill people's ears with such pleasure. The sound cleared its own space and made it seem like everything was okay again.",
  'You once thought of me as a white knight on his steed. Now you know how happy I can be. Our good times start and end without dollar one to spend.',
  'If I could fall into the sky, do you think time would pass me by?',
  "I don't give a damn, except that I get bored sometimes when people tell me to act my age. Sometimes I act a lot older than I am - I really do - but people never notice it. People never notice anything.",
  'Sometimes I wondered if I was seeing the same things through my eyes that the rest of the world was seeing through theirs. Maybe there was a glitch in my brain.',
  'To the extent that experience is the sum of our memories and wisdom the sum of experience, having a better memory would mean knowing not only more about the world, but also more about myself.',
  "Everyone is to blame. He says that when you separate people into groups, they start to believe that one group is better than another. I think about Papa's medical books and how we all have the same blood, and organs, and bones inside us, no matter what religion we're supposed to be.",
  "And you can find me where the sea pours into the stars, I'll get there someday. I hope you find everything you think that you want. Bruises will fade, time on our side, we can wait for it. I'll be doing fine, if you are, 'cause life is but a dream; only as real as you let it be.",
  "You had to kill the conversation, you always had the upper hand. Got caught in love and stepped in sinking sand. You had to go and ruin all our plans, packed your bags and you're leaving home. Got a one-way ticket and you're all set to go, but we have one more day together, so love me like there's no tomorrow.",
  "You know, Doc, when something happens, it can leave a trace of itself behind. Say like if someone burns toast. Well, maybe things that happen leave other kinds of traces behind. Not things that anyone can notice, but things that people who shine can see. Just like they can see things that haven't happened yet, well, sometimes they can see things that happened a long time ago. I think a lot of things happened right here in this particular hotel over the years, and not all of 'em was good.",
  'When every card in the deck is stacked against you, the only way to win a hand is to break the rules.',
  "I don't want to set the world on fire, I just want to start a flame in your heart. In my heart I have but one desire, and that one is you, no other will do. I've lost all ambition for worldly acclaim, I just want to be the one you love. And with your admission that you feel the same, I'll have reached the goal I'm dreaming of, believe me.",
  "Last night we said a great many things. You said I was to do the thinking for both of us. Well, I've done a lot of it since then, and it all adds up to one thing: you're getting on that plane with Victor where you belong.",
  "I thought I had it all together, but I was led astray the day you walked away. You were the clock that was tickin' in my home. Changed my state of mind. Love's so hard to find.",
  "I wish I could just make you turn around and see me cry. There's so much I need to say to you. So many reasons why you're the only one who really knew me at all.",
  'I am sitting in the morning at the diner on the corner. I am waiting at the counter for the man to pour the coffee, and he fills it only halfway, and before I even argue, he is looking out the window at somebody coming in.',
  "So, I guess we are who we are for a lot of reasons. And maybe we'll never know most of them. But even if we don't have the power to choose where we come from, we can still choose where we go from there. We can still do things. And we can try to feel okay about them.",
  "It's just that I learned a while ago that the best way to get people to like you is not to like them too much.",
  "If we burn our wings flying too close to the sun; if the moment of glory is over before it's begun; if the dream is won though everything is lost, we will pay the price but we will not count the cost.",
  'The capacity to love is determined by the fact that man is ready to seek the good consciously with others, to subordinate himself to this good because of others, or to subordinate himself to others because of this good.',
  "You don't know what you're trying to take from me. You don't like it messy, but it's going to get as messy as it wants to be. Wind me up, set me down and look away. I can see the bottom, and the bottom's okay.",
  "What are you doing on my boat? Look, I've had a really bad day and I just need your help. You see, I've been thrown out of my home and flushed down my own toilet.",
  'Dreams are not to be converted into reality, that we know; we would not form any, perhaps, were it not for desire, and it is useful to us to form them in order to see them fail and to be instructed by their failure.',
  "After I finish, it's like the part of me that can't fall asleep, the part that's staring at the cracks on the ceiling, wondering and worrying, is emptied in the diary for the night. During the day I fill back up and the pages wait. I like to think you're holding my thoughts for me until I can tend to them again.",
  "You're horrible. You make up this story about demons talking to you through plastic animals when nothing talks to you just like nothing talks to me.",
  "You are the promised kiss of springtime that makes the lonely winter seem long. You are the breathless hush of evening that trembles on the brink of a lovely song. You are the angel glow that lights a star, the dearest things I know are what you are. Some day my happy arms will hold you, and some day I'll know that moment divine when all the things you are, are mine.",
  'Where did I go wrong? I lost a friend somewhere along in the bitterness and I would have stayed up with you all night had I known how to save a life.',
  "There's an old voice in my head that's holding me back. Well, tell her that I miss our little talks. Soon it will be over and buried with our past. We used to play outside when we were young and full of life and full of love.",
  'We can experience nothing but the present moment, live in no other second of time, and to understand this is as close as we can get to eternal life.',
  "Can you feel the sunshine? Does it brighten up your day? Don't you feel that sometimes you just need to run away? Reach out for the sunshine, forget about the rain. Just think about the good times and they will come back again.",
  'One of the most tragic things I know about human nature is that all of us tend to put off living. We are all dreaming of some magical rose garden over the horizon instead of enjoying the roses that are blooming outside our windows today.',
  "Everyone wants stuff. We wake up every day with a list of wishes a mile long and maybe we spend our lives trying to make those wishes come true, but just because we want them doesn't mean we need them to be happy.",
  'Sam was the only member of the party who had not been over the river before. He had a strange feeling as the slow gurgling stream slipped by: his old life lay behind him in the mists, dark adventure lay in front.',
  "The place to improve the world is first in one's own heart and head and hands, and then to work outward from there. Other people can talk about how to expand the destiny of mankind. I just want to talk about how to fix a motorcycle. I think that what I have to say has more lasting value.",
  'We imagine that when we are thrown out of our usual ruts all is lost, but it is only then that what is new and good begins. While there is life there is happiness. There is much, much before us.',
  'Nothing makes time pass or shortens the way like a thought that absorbs in itself all the faculties of the one who is thinking. External existence is then like a sleep of which this thought is the dream. Under its influence, time has no more measure, space has no more distance.',
  "When for years you wake up to having to win every battle every day, to prove that you are the best at everything... I started to worry what would happen if it turned out that I wasn't the best. I didn't want to worry...",
  "Well, if that's how you feel about it, then that's how you feel about it. Is that how you feel about it?",
  'The last man on Earth sat alone in a room. There was a knock on the door.',
  'He supposed that even in Hell, people got an occasional sip of water, if only so they could appreciate the full horror of unrequited thirst when it set in again.',
  "I'll close my eyes. Then I won't see the love you don't feel when you're holding me. Morning will come, and I'll do what's right. Just give me till then to give up this fight.",
  'Remember that humor is written backwards. That means you first find the cliche you want to work on, then build a story around it.',
  "Now and again we try to just stay alive, maybe we'll turn it all around 'cause it's not too late. It's never too late.",
  'We never get to change the past. We never get to know the future. No reason to wish for one place rather than another; no reason to say I wish I were home, or I wish I were in an exotic new place that is not my home. They will all be the same as this place. Here the experience of existing comes clear. This world is our body.',
  'A straight line is said to have been cut in extreme and mean ratio when, as the whole line is to the greater segment, so is the greater to the lesser.',
  "Why did I do it? Mainly because people said it was impossible, and that's what my life is all about: breaking limitations and showing people what our memories are capable of.",
  'The example of painting can teach us not only how to manage our own work, but how to work together. A lot of the great art of the past is the work of multiple hands, though there may only be one name on the wall next to it in the museum.',
  'Live a good life. If there are gods and they are just, they will not care how devout you have been, but will welcome you based on the virtues you have lived by. If there are gods, but unjust, then you should not want to worship them. If there are no gods, then you will be gone, but will have lived a noble life that will live on in the memories of your loved ones.',
  'I can hear the soft breathing of the girl that I love as she lies here beside me asleep with the night. And her hair, in a fine mist floats on my pillow, reflecting the glow of the winter moonlight.',
  'And the hardest part was letting go, not taking part was the hardest part. And the strangest thing was waiting for that bell to ring. It was the strangest start.',
  'For my hope was founded on a fat man in Bree; and my fear was founded on the cunning of Sauron. But fat men who sell ale have many calls to answer; and the power of Sauron is still less than fear makes it.',
  'It is not despair, for despair is only for those who see the end beyond all doubt. We do not.',
  'We all start out knowing magic. We are born with whirlwinds, forest fires, and comets inside us. We are born able to sing to birds and read the clouds and see our destiny in grains of sand. But then we get the magic educated right out of our souls.',
  "We've wounded this mountain. It's our duty to close her wounds. It's the least we can do to show our gratitude for all the wealth she's given us. If you guys don't want to help me, I'll do it alone.",
  "I've never really had much of an imagination. But still I would try to picture the exact moment when the beating of my heart would no longer be going on inside my head.",
  "And I taught myself how to forget that sometimes life will try to convince you there's such a thing as regret. But I found it to be a lie, the same lie I found when I looked in your eyes after it was said and done.",
  'If you had one shot to sit on your lazy butt, and watch all the TV you ever wanted, until your brain turned to mush. Would you go for it, or just let it slip?',
  "I shall die here. Every last inch of me shall perish. Except one. An inch. It's small and it's fragile and it's the only thing in the world worth having. We must never lose it, or sell it, or give it away. We must never let them take it from us.",
  "I've never been to this part of the castle, at least while awake. I sleepwalk you see, that's why I wear shoes to bed.",
  "Look into my eyes and it's easy to see, one and one make two, two and one make three, it was destiny. Once every hundred thousand years or so, when the sun doth shine and the moon doth glow and the grass doth grow.",
  "It's been rainy and windy for seven days straight. I've been going to bed early and getting up late. I look out my window and it's one shade of gray. My wife and my kids don't have much to say. A man out of work only gets in the way.",
  'In the midst of friends, home, and kind parents, she was alone.',
  'She would follow, her dream of love, the dictates of her heart that told her he was her all in all, the only man in all the world for her for love was the master guide. Come what might she would be wild, untrammelled, free.',
  "It seemed funny to me that the sunset she saw from her patio and the one I saw from the back steps was the same one. Maybe the two different worlds we lived in weren't so different. We saw the same sunset.",
  'When you hit rock-bottom, you still have a way to go until the abyss.',
  'It was not the brutality of what occurred next that changed my mind and brought home to me the full meaning of fear. It was the brilliance of it.',
  "The point is you've got to get to know each other better if you're going to take a big step like this. You gotta get past this early infatuation and get to the point where you're sick and tired of each other; then you're ready for marriage. Look at Diane and me, we waited five years to get married. If it were up to me we'd wait another five.",
  'I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.',
  'There is a theory, for which there is much to be said, that gold and gems were valued originally on account of their supposed magical properties.',
  "Every day when you're walking down the street, everybody that you meet has an original point of view. And I say hey, hey! What a wonderful kind of day, where you can learn to work and play, and get along with each other.",
  'In the beginning, the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.',
  "Picture a wave in the ocean. You can see it, measure it, its height, the way the sunlight refracts when it passes through, and it's there, and you can see it, you know what it is. It's a wave. And then it crashes on the shore, and it's gone. But the water is still there. The wave was just a different way for the water to be for a little while.",
  'I want you to know that the day you saw something in me, my whole life changed.',
  'Your silence furnishes a dark house. But even at the risk of burning, the moth always seeks the light.',
  'It was the last that remained of a past whose annihilation had not taken place because it was still in a process of annihilation, consuming itself from within, ending at every moment but never ending its ending.',
  'The gentleman cannot be appreciated in small things but is acceptable in great matters. A small man is not acceptable in great matters but can be appreciated in small things.',
  "There was no reason for me to stay in the real world any longer. In the real world, it didn't matter if I was there or not. When I realized that, I was no longer afraid of losing my body.",
  "There's a storm coming, Mr. Wayne. You and your friends better batten down the hatches, because when it hits, you're all gonna wonder how you ever thought you could live so large and leave so little for the rest of us.",
];
