name: Scrape Payphone data

on:
  schedule:
    - cron: '17 */6 * * *'
  workflow_dispatch:

jobs:
  payphone_scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Python Script
        run: python payphones/cors_proxy.py # Replace with your actual script filename

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
